language: rust
rust:
  - 1.35.0
  - stable
  - beta
  - nightly
before_script:
  - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo clippy -- -D warnings
  - cargo test
matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true
