[package]
name = "human_resource_machine"
version = "0.3.0"
authors = ["Max Blachman <blachmanmax@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
quickcheck = "0.8"
quickcheck_macros = "0.8"